export enum ErrorCode {
  INVALID_AMOUNT = 'INVALID_AMOUNT',
  CURRENCY_MISMATCH = 'CURRENCY_MISMATCH',
  NEGATIVE_AMOUNT_NOT_ALLOWED = 'NEGATIVE_AMOUNT_NOT_ALLOWED',
  LEDGER_UNBALANCED = 'LEDGER_UNBALANCED',
  INVALID_ACCOUNT_TYPE = 'INVALID_ACCOUNT_TYPE',
  INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',
  RULE_VIOLATION = 'RULE_VIOLATION',
  KYC_FAILED = 'KYC_FAILED',
  AML_FLAGGED = 'AML_FLAGGED',
  COUNTRY_RESTRICTED = 'COUNTRY_RESTRICTED',
  AMOUNT_THRESHOLD_EXCEEDED = 'AMOUNT_THRESHOLD_EXCEEDED',
  IDEMPOTENCY_KEY_IN_USE = 'IDEMPOTENCY_KEY_IN_USE',
  IDEMPOTENCY_PAYLOAD_MISMATCH = 'IDEMPOTENCY_PAYLOAD_MISMATCH',
  INVALID_STATE_TRANSITION = 'INVALID_STATE_TRANSITION',
  ENTITY_NOT_FOUND = 'ENTITY_NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  PROVIDER_ERROR = 'PROVIDER_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  AUDIT_IMMUTABLE_ERROR = 'AUDIT_IMMUTABLE_ERROR'
}

export class DomainError extends Error {
  public readonly code: ErrorCode;
  public readonly details?: Record<string, unknown>;

  constructor(code: ErrorCode, message: string, details?: Record<string, unknown>) {
    super(message);
    this.name = 'DomainError';
    this.code = code;
    this.details = details;
    Object.setPrototypeOf(this, DomainError.prototype);
  }
}
